spring.application.name=tst-manage
server.port=${PORT:8080}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db.aabhyazfeeiwegchfxrl.supabase.co:5432/postgres?user=postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DB_USERNAME:postgres}}
spring.datasource.password=${DB_PASSWORD:%23%40%24Htag0901}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.error.include-message=always
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect