spring.application.name=tst-manage
server.port=${PORT:8080}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DB_USERNAME:postgres.aabhyazfeeiwegchfxrl}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:#@$Htag0901}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.error.include-message=always